// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rule.proto

package rule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvocationMode int32

const (
	InvocationMode_MODE_UNSPECIFIED InvocationMode = 0
	InvocationMode_MODE_COMPILE     InvocationMode = 1
	InvocationMode_MODE_VERIFY      InvocationMode = 2
)

// Enum value maps for InvocationMode.
var (
	InvocationMode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_COMPILE",
		2: "MODE_VERIFY",
	}
	InvocationMode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_COMPILE":     1,
		"MODE_VERIFY":      2,
	}
)

func (x InvocationMode) Enum() *InvocationMode {
	p := new(InvocationMode)
	*p = x
	return p
}

func (x InvocationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[0].Descriptor()
}

func (InvocationMode) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[0]
}

func (x InvocationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationMode.Descriptor instead.
func (InvocationMode) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{0}
}

type SelectorKind int32

const (
	SelectorKind_SELECTOR_UNSPECIFIED SelectorKind = 0
	SelectorKind_SELECTOR_COMPONENT   SelectorKind = 4
	SelectorKind_SELECTOR_CLASS       SelectorKind = 5
	SelectorKind_SELECTOR_INTERFACE   SelectorKind = 6
	SelectorKind_SELECTOR_PATH        SelectorKind = 7
)

// Enum value maps for SelectorKind.
var (
	SelectorKind_name = map[int32]string{
		0: "SELECTOR_UNSPECIFIED",
		4: "SELECTOR_COMPONENT",
		5: "SELECTOR_CLASS",
		6: "SELECTOR_INTERFACE",
		7: "SELECTOR_PATH",
	}
	SelectorKind_value = map[string]int32{
		"SELECTOR_UNSPECIFIED": 0,
		"SELECTOR_COMPONENT":   4,
		"SELECTOR_CLASS":       5,
		"SELECTOR_INTERFACE":   6,
		"SELECTOR_PATH":        7,
	}
)

func (x SelectorKind) Enum() *SelectorKind {
	p := new(SelectorKind)
	*p = x
	return p
}

func (x SelectorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[1].Descriptor()
}

func (SelectorKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[1]
}

func (x SelectorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectorKind.Descriptor instead.
func (SelectorKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{1}
}

type RuleKind int32

const (
	RuleKind_RULE_UNSPECIFIED     RuleKind = 0
	RuleKind_RULE_DEPEND_ONLY     RuleKind = 1  // "must only depend on"
	RuleKind_RULE_NOT_DEPEND      RuleKind = 2  // "must not depend on"
	RuleKind_RULE_ANNOTATE        RuleKind = 3  // "must be annotated with"
	RuleKind_RULE_NOT_ANNOTATE    RuleKind = 4  // "must not be annotated with"
	RuleKind_RULE_EXTEND          RuleKind = 5  // "must extend class"
	RuleKind_RULE_NOT_EXTEND      RuleKind = 6  // "must not extend class"
	RuleKind_RULE_IMPLEMENT       RuleKind = 7  // "must implement interface"
	RuleKind_RULE_NOT_IMPLEMENT   RuleKind = 8  // "must not implement interface"
	RuleKind_RULE_ACCESSED_BY     RuleKind = 9  // "must only be accessed by"
	RuleKind_RULE_ACYCLIC         RuleKind = 10 // "must be acyclic"
	RuleKind_RULE_IN              RuleKind = 11 // "must be in"
	RuleKind_RULE_NOT_IN          RuleKind = 12 // "must not be in"
	RuleKind_RULE_MATCH           RuleKind = 13 // "must match"
	RuleKind_RULE_NOT_MATCH       RuleKind = 14 // "must not match"
	RuleKind_RULE_VISIBILITY      RuleKind = 15 // "must be public/internal/private"
	RuleKind_RULE_TYPE_CONSTRAINT RuleKind = 16 // "must be abstract/sealed/static"
)

// Enum value maps for RuleKind.
var (
	RuleKind_name = map[int32]string{
		0:  "RULE_UNSPECIFIED",
		1:  "RULE_DEPEND_ONLY",
		2:  "RULE_NOT_DEPEND",
		3:  "RULE_ANNOTATE",
		4:  "RULE_NOT_ANNOTATE",
		5:  "RULE_EXTEND",
		6:  "RULE_NOT_EXTEND",
		7:  "RULE_IMPLEMENT",
		8:  "RULE_NOT_IMPLEMENT",
		9:  "RULE_ACCESSED_BY",
		10: "RULE_ACYCLIC",
		11: "RULE_IN",
		12: "RULE_NOT_IN",
		13: "RULE_MATCH",
		14: "RULE_NOT_MATCH",
		15: "RULE_VISIBILITY",
		16: "RULE_TYPE_CONSTRAINT",
	}
	RuleKind_value = map[string]int32{
		"RULE_UNSPECIFIED":     0,
		"RULE_DEPEND_ONLY":     1,
		"RULE_NOT_DEPEND":      2,
		"RULE_ANNOTATE":        3,
		"RULE_NOT_ANNOTATE":    4,
		"RULE_EXTEND":          5,
		"RULE_NOT_EXTEND":      6,
		"RULE_IMPLEMENT":       7,
		"RULE_NOT_IMPLEMENT":   8,
		"RULE_ACCESSED_BY":     9,
		"RULE_ACYCLIC":         10,
		"RULE_IN":              11,
		"RULE_NOT_IN":          12,
		"RULE_MATCH":           13,
		"RULE_NOT_MATCH":       14,
		"RULE_VISIBILITY":      15,
		"RULE_TYPE_CONSTRAINT": 16,
	}
)

func (x RuleKind) Enum() *RuleKind {
	p := new(RuleKind)
	*p = x
	return p
}

func (x RuleKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[2].Descriptor()
}

func (RuleKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[2]
}

func (x RuleKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleKind.Descriptor instead.
func (RuleKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{2}
}

type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	Visibility_VISIBILITY_PUBLIC      Visibility = 1
	Visibility_VISIBILITY_INTERNAL    Visibility = 2
	Visibility_VISIBILITY_PRIVATE     Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PUBLIC",
		2: "VISIBILITY_INTERNAL",
		3: "VISIBILITY_PRIVATE",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PUBLIC":      1,
		"VISIBILITY_INTERNAL":    2,
		"VISIBILITY_PRIVATE":     3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[3].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[3]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{3}
}

type TypeConstraint int32

const (
	TypeConstraint_TYPE_CONSTRAINT_UNSPECIFIED TypeConstraint = 0
	TypeConstraint_TYPE_CONSTRAINT_ABSTRACT    TypeConstraint = 1
	TypeConstraint_TYPE_CONSTRAINT_SEALED      TypeConstraint = 2
	TypeConstraint_TYPE_CONSTRAINT_STATIC      TypeConstraint = 3
)

// Enum value maps for TypeConstraint.
var (
	TypeConstraint_name = map[int32]string{
		0: "TYPE_CONSTRAINT_UNSPECIFIED",
		1: "TYPE_CONSTRAINT_ABSTRACT",
		2: "TYPE_CONSTRAINT_SEALED",
		3: "TYPE_CONSTRAINT_STATIC",
	}
	TypeConstraint_value = map[string]int32{
		"TYPE_CONSTRAINT_UNSPECIFIED": 0,
		"TYPE_CONSTRAINT_ABSTRACT":    1,
		"TYPE_CONSTRAINT_SEALED":      2,
		"TYPE_CONSTRAINT_STATIC":      3,
	}
)

func (x TypeConstraint) Enum() *TypeConstraint {
	p := new(TypeConstraint)
	*p = x
	return p
}

func (x TypeConstraint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeConstraint) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[4].Descriptor()
}

func (TypeConstraint) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[4]
}

func (x TypeConstraint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeConstraint.Descriptor instead.
func (TypeConstraint) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{4}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_ERROR       Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_WARNING":     2,
		"SEVERITY_ERROR":       3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[5].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[5]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{5}
}

type ExcludeKind int32

const (
	ExcludeKind_EXCLUDE_UNSPECIFIED         ExcludeKind = 0
	ExcludeKind_EXCLUDE_CLASS               ExcludeKind = 4
	ExcludeKind_EXCLUDE_IMPLEMENT_INTERFACE ExcludeKind = 3
	ExcludeKind_EXCLUDE_COMPONENT           ExcludeKind = 5
)

// Enum value maps for ExcludeKind.
var (
	ExcludeKind_name = map[int32]string{
		0: "EXCLUDE_UNSPECIFIED",
		4: "EXCLUDE_CLASS",
		3: "EXCLUDE_IMPLEMENT_INTERFACE",
		5: "EXCLUDE_COMPONENT",
	}
	ExcludeKind_value = map[string]int32{
		"EXCLUDE_UNSPECIFIED":         0,
		"EXCLUDE_CLASS":               4,
		"EXCLUDE_IMPLEMENT_INTERFACE": 3,
		"EXCLUDE_COMPONENT":           5,
	}
)

func (x ExcludeKind) Enum() *ExcludeKind {
	p := new(ExcludeKind)
	*p = x
	return p
}

func (x ExcludeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExcludeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[6].Descriptor()
}

func (ExcludeKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[6]
}

func (x ExcludeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExcludeKind.Descriptor instead.
func (ExcludeKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{6}
}

type CheckKind int32

const (
	CheckKind_CHECK_UNSPECIFIED         CheckKind = 0
	CheckKind_CHECK_FS_MUST_EXIST       CheckKind = 1
	CheckKind_CHECK_FS_MUST_NOT_EXIST   CheckKind = 2
	CheckKind_CHECK_FS_MUST_CONTAIN     CheckKind = 3
	CheckKind_CHECK_FS_MUST_NOT_CONTAIN CheckKind = 4
)

// Enum value maps for CheckKind.
var (
	CheckKind_name = map[int32]string{
		0: "CHECK_UNSPECIFIED",
		1: "CHECK_FS_MUST_EXIST",
		2: "CHECK_FS_MUST_NOT_EXIST",
		3: "CHECK_FS_MUST_CONTAIN",
		4: "CHECK_FS_MUST_NOT_CONTAIN",
	}
	CheckKind_value = map[string]int32{
		"CHECK_UNSPECIFIED":         0,
		"CHECK_FS_MUST_EXIST":       1,
		"CHECK_FS_MUST_NOT_EXIST":   2,
		"CHECK_FS_MUST_CONTAIN":     3,
		"CHECK_FS_MUST_NOT_CONTAIN": 4,
	}
)

func (x CheckKind) Enum() *CheckKind {
	p := new(CheckKind)
	*p = x
	return p
}

func (x CheckKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[7].Descriptor()
}

func (CheckKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[7]
}

func (x CheckKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckKind.Descriptor instead.
func (CheckKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{7}
}

type SpecIR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputDir     string                 `protobuf:"bytes,1,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	Adr           *AdrIR                 `protobuf:"bytes,2,opt,name=adr,proto3" json:"adr,omitempty"`
	Selectors     []*SelectorIR          `protobuf:"bytes,3,rep,name=selectors,proto3" json:"selectors,omitempty"`
	Rules         []*RuleIR              `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	Mode          InvocationMode         `protobuf:"varint,16,opt,name=mode,proto3,enum=rule.InvocationMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecIR) Reset() {
	*x = SpecIR{}
	mi := &file_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecIR) ProtoMessage() {}

func (x *SpecIR) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecIR.ProtoReflect.Descriptor instead.
func (*SpecIR) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{0}
}

func (x *SpecIR) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *SpecIR) GetAdr() *AdrIR {
	if x != nil {
		return x.Adr
	}
	return nil
}

func (x *SpecIR) GetSelectors() []*SelectorIR {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *SpecIR) GetRules() []*RuleIR {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SpecIR) GetMode() InvocationMode {
	if x != nil {
		return x.Mode
	}
	return InvocationMode_MODE_UNSPECIFIED
}

type AdrIR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdrIR) Reset() {
	*x = AdrIR{}
	mi := &file_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdrIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdrIR) ProtoMessage() {}

func (x *AdrIR) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdrIR.ProtoReflect.Descriptor instead.
func (*AdrIR) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{1}
}

func (x *AdrIR) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdrIR) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SelectorIR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"` // package/namespace root or glob pattern
	Kind          SelectorKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=rule.SelectorKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectorIR) Reset() {
	*x = SelectorIR{}
	mi := &file_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectorIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorIR) ProtoMessage() {}

func (x *SelectorIR) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorIR.ProtoReflect.Descriptor instead.
func (*SelectorIR) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{2}
}

func (x *SelectorIR) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SelectorIR) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SelectorIR) GetKind() SelectorKind {
	if x != nil {
		return x.Kind
	}
	return SelectorKind_SELECTOR_UNSPECIFIED
}

type ExclusionIR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ExcludeKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=rule.ExcludeKind" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExclusionIR) Reset() {
	*x = ExclusionIR{}
	mi := &file_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExclusionIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusionIR) ProtoMessage() {}

func (x *ExclusionIR) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusionIR.ProtoReflect.Descriptor instead.
func (*ExclusionIR) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{3}
}

func (x *ExclusionIR) GetKind() ExcludeKind {
	if x != nil {
		return x.Kind
	}
	return ExcludeKind_EXCLUDE_UNSPECIFIED
}

func (x *ExclusionIR) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// TargetRefIR represents a subject or target in a rule
// Can be a selector reference or an inline pattern
type TargetRefIR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                        // selector name or pattern string
	IsInline      bool                   `protobuf:"varint,2,opt,name=is_inline,json=isInline,proto3" json:"is_inline,omitempty"` // true if inline pattern (not a selector reference)
	Type          SelectorKind           `protobuf:"varint,3,opt,name=type,proto3,enum=rule.SelectorKind" json:"type,omitempty"`  // type for inline patterns only
	IsMatch       bool                   `protobuf:"varint,4,opt,name=is_match,json=isMatch,proto3" json:"is_match,omitempty"`    // true if "match" pattern (regex)
	Scope         *TargetRefIR           `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`                        // optional "in" scope (subset relation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRefIR) Reset() {
	*x = TargetRefIR{}
	mi := &file_rule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRefIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRefIR) ProtoMessage() {}

func (x *TargetRefIR) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRefIR.ProtoReflect.Descriptor instead.
func (*TargetRefIR) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{4}
}

func (x *TargetRefIR) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TargetRefIR) GetIsInline() bool {
	if x != nil {
		return x.IsInline
	}
	return false
}

func (x *TargetRefIR) GetType() SelectorKind {
	if x != nil {
		return x.Type
	}
	return SelectorKind_SELECTOR_UNSPECIFIED
}

func (x *TargetRefIR) GetIsMatch() bool {
	if x != nil {
		return x.IsMatch
	}
	return false
}

func (x *TargetRefIR) GetScope() *TargetRefIR {
	if x != nil {
		return x.Scope
	}
	return nil
}

type RuleIR struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind  RuleKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=rule.RuleKind" json:"kind,omitempty"`
	// Subject of the rule (was "from" in old syntax)
	From *TargetRefIR `protobuf:"bytes,8,opt,name=from,proto3" json:"from,omitempty"`
	// Targets (dependencies, interface, etc.)
	Targets  []*TargetRefIR `protobuf:"bytes,9,rep,name=targets,proto3" json:"targets,omitempty"`
	Severity Severity       `protobuf:"varint,5,opt,name=severity,proto3,enum=rule.Severity" json:"severity,omitempty"`
	Excludes []*ExclusionIR `protobuf:"bytes,6,rep,name=excludes,proto3" json:"excludes,omitempty"`
	// Scanner checks within a rule block
	Checks []*CheckIR `protobuf:"bytes,7,rep,name=checks,proto3" json:"checks,omitempty"`
	// For visibility rules
	Visibility Visibility `protobuf:"varint,10,opt,name=visibility,proto3,enum=rule.Visibility" json:"visibility,omitempty"`
	// For type constraint rules
	TypeConstraint TypeConstraint `protobuf:"varint,11,opt,name=type_constraint,json=typeConstraint,proto3,enum=rule.TypeConstraint" json:"type_constraint,omitempty"`
	// Rule category: true for file rules, false for code rules
	IsFileRule bool `protobuf:"varint,12,opt,name=is_file_rule,json=isFileRule,proto3" json:"is_file_rule,omitempty"`
	// Custom rule fields (opaque block; body is forwarded to the plugin unchanged)
	IsCustomRule  bool   `protobuf:"varint,13,opt,name=is_custom_rule,json=isCustomRule,proto3" json:"is_custom_rule,omitempty"`
	RawBody       string `protobuf:"bytes,15,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleIR) Reset() {
	*x = RuleIR{}
	mi := &file_rule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleIR) ProtoMessage() {}

func (x *RuleIR) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleIR.ProtoReflect.Descriptor instead.
func (*RuleIR) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{5}
}

func (x *RuleIR) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleIR) GetKind() RuleKind {
	if x != nil {
		return x.Kind
	}
	return RuleKind_RULE_UNSPECIFIED
}

func (x *RuleIR) GetFrom() *TargetRefIR {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *RuleIR) GetTargets() []*TargetRefIR {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *RuleIR) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *RuleIR) GetExcludes() []*ExclusionIR {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *RuleIR) GetChecks() []*CheckIR {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *RuleIR) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *RuleIR) GetTypeConstraint() TypeConstraint {
	if x != nil {
		return x.TypeConstraint
	}
	return TypeConstraint_TYPE_CONSTRAINT_UNSPECIFIED
}

func (x *RuleIR) GetIsFileRule() bool {
	if x != nil {
		return x.IsFileRule
	}
	return false
}

func (x *RuleIR) GetIsCustomRule() bool {
	if x != nil {
		return x.IsCustomRule
	}
	return false
}

func (x *RuleIR) GetRawBody() string {
	if x != nil {
		return x.RawBody
	}
	return ""
}

type CheckIR struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  CheckKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=rule.CheckKind" json:"kind,omitempty"`
	// Path pattern (now string literals without "glob:" prefix)
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// For *contain* checks: literal string or "regex:..." pattern
	Pattern       string `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIR) Reset() {
	*x = CheckIR{}
	mi := &file_rule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIR) ProtoMessage() {}

func (x *CheckIR) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIR.ProtoReflect.Descriptor instead.
func (*CheckIR) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{6}
}

func (x *CheckIR) GetKind() CheckKind {
	if x != nil {
		return x.Kind
	}
	return CheckKind_CHECK_UNSPECIFIED
}

func (x *CheckIR) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CheckIR) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

var File_rule_proto protoreflect.FileDescriptor

const file_rule_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rule.proto\x12\x04rule\"\xc4\x01\n" +
	"\x06SpecIR\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x01 \x01(\tR\toutputDir\x12\x1d\n" +
	"\x03adr\x18\x02 \x01(\v2\v.rule.AdrIRR\x03adr\x12.\n" +
	"\tselectors\x18\x03 \x03(\v2\x10.rule.SelectorIRR\tselectors\x12\"\n" +
	"\x05rules\x18\x04 \x03(\v2\f.rule.RuleIRR\x05rules\x12(\n" +
	"\x04mode\x18\x10 \x01(\x0e2\x14.rule.InvocationModeR\x04mode\"-\n" +
	"\x05AdrIR\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"b\n" +
	"\n" +
	"SelectorIR\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12&\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x12.rule.SelectorKindR\x04kind\"J\n" +
	"\vExclusionIR\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.rule.ExcludeKindR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xac\x01\n" +
	"\vTargetRefIR\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1b\n" +
	"\tis_inline\x18\x02 \x01(\bR\bisInline\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.rule.SelectorKindR\x04type\x12\x19\n" +
	"\bis_match\x18\x04 \x01(\bR\aisMatch\x12'\n" +
	"\x05scope\x18\x05 \x01(\v2\x11.rule.TargetRefIRR\x05scope\"\xea\x03\n" +
	"\x06RuleIR\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x0e.rule.RuleKindR\x04kind\x12%\n" +
	"\x04from\x18\b \x01(\v2\x11.rule.TargetRefIRR\x04from\x12+\n" +
	"\atargets\x18\t \x03(\v2\x11.rule.TargetRefIRR\atargets\x12*\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x0e.rule.SeverityR\bseverity\x12-\n" +
	"\bexcludes\x18\x06 \x03(\v2\x11.rule.ExclusionIRR\bexcludes\x12%\n" +
	"\x06checks\x18\a \x03(\v2\r.rule.CheckIRR\x06checks\x120\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\x0e2\x10.rule.VisibilityR\n" +
	"visibility\x12=\n" +
	"\x0ftype_constraint\x18\v \x01(\x0e2\x14.rule.TypeConstraintR\x0etypeConstraint\x12 \n" +
	"\fis_file_rule\x18\f \x01(\bR\n" +
	"isFileRule\x12$\n" +
	"\x0eis_custom_rule\x18\r \x01(\bR\fisCustomRule\x12\x19\n" +
	"\braw_body\x18\x0f \x01(\tR\arawBody\"\\\n" +
	"\aCheckIR\x12#\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x0f.rule.CheckKindR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern*I\n" +
	"\x0eInvocationMode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMODE_COMPILE\x10\x01\x12\x0f\n" +
	"\vMODE_VERIFY\x10\x02*\x7f\n" +
	"\fSelectorKind\x12\x18\n" +
	"\x14SELECTOR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SELECTOR_COMPONENT\x10\x04\x12\x12\n" +
	"\x0eSELECTOR_CLASS\x10\x05\x12\x16\n" +
	"\x12SELECTOR_INTERFACE\x10\x06\x12\x11\n" +
	"\rSELECTOR_PATH\x10\a*\xe0\x02\n" +
	"\bRuleKind\x12\x14\n" +
	"\x10RULE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RULE_DEPEND_ONLY\x10\x01\x12\x13\n" +
	"\x0fRULE_NOT_DEPEND\x10\x02\x12\x11\n" +
	"\rRULE_ANNOTATE\x10\x03\x12\x15\n" +
	"\x11RULE_NOT_ANNOTATE\x10\x04\x12\x0f\n" +
	"\vRULE_EXTEND\x10\x05\x12\x13\n" +
	"\x0fRULE_NOT_EXTEND\x10\x06\x12\x12\n" +
	"\x0eRULE_IMPLEMENT\x10\a\x12\x16\n" +
	"\x12RULE_NOT_IMPLEMENT\x10\b\x12\x14\n" +
	"\x10RULE_ACCESSED_BY\x10\t\x12\x10\n" +
	"\fRULE_ACYCLIC\x10\n" +
	"\x12\v\n" +
	"\aRULE_IN\x10\v\x12\x0f\n" +
	"\vRULE_NOT_IN\x10\f\x12\x0e\n" +
	"\n" +
	"RULE_MATCH\x10\r\x12\x12\n" +
	"\x0eRULE_NOT_MATCH\x10\x0e\x12\x13\n" +
	"\x0fRULE_VISIBILITY\x10\x0f\x12\x18\n" +
	"\x14RULE_TYPE_CONSTRAINT\x10\x10*p\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x01\x12\x17\n" +
	"\x13VISIBILITY_INTERNAL\x10\x02\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x03*\x87\x01\n" +
	"\x0eTypeConstraint\x12\x1f\n" +
	"\x1bTYPE_CONSTRAINT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TYPE_CONSTRAINT_ABSTRACT\x10\x01\x12\x1a\n" +
	"\x16TYPE_CONSTRAINT_SEALED\x10\x02\x12\x1a\n" +
	"\x16TYPE_CONSTRAINT_STATIC\x10\x03*N\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x03*q\n" +
	"\vExcludeKind\x12\x17\n" +
	"\x13EXCLUDE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rEXCLUDE_CLASS\x10\x04\x12\x1f\n" +
	"\x1bEXCLUDE_IMPLEMENT_INTERFACE\x10\x03\x12\x15\n" +
	"\x11EXCLUDE_COMPONENT\x10\x05*\x92\x01\n" +
	"\tCheckKind\x12\x15\n" +
	"\x11CHECK_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHECK_FS_MUST_EXIST\x10\x01\x12\x1b\n" +
	"\x17CHECK_FS_MUST_NOT_EXIST\x10\x02\x12\x19\n" +
	"\x15CHECK_FS_MUST_CONTAIN\x10\x03\x12\x1d\n" +
	"\x19CHECK_FS_MUST_NOT_CONTAIN\x10\x04B\bZ\x06./ruleb\x06proto3"

var (
	file_rule_proto_rawDescOnce sync.Once
	file_rule_proto_rawDescData []byte
)

func file_rule_proto_rawDescGZIP() []byte {
	file_rule_proto_rawDescOnce.Do(func() {
		file_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rule_proto_rawDesc), len(file_rule_proto_rawDesc)))
	})
	return file_rule_proto_rawDescData
}

var file_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rule_proto_goTypes = []any{
	(InvocationMode)(0), // 0: rule.InvocationMode
	(SelectorKind)(0),   // 1: rule.SelectorKind
	(RuleKind)(0),       // 2: rule.RuleKind
	(Visibility)(0),     // 3: rule.Visibility
	(TypeConstraint)(0), // 4: rule.TypeConstraint
	(Severity)(0),       // 5: rule.Severity
	(ExcludeKind)(0),    // 6: rule.ExcludeKind
	(CheckKind)(0),      // 7: rule.CheckKind
	(*SpecIR)(nil),      // 8: rule.SpecIR
	(*AdrIR)(nil),       // 9: rule.AdrIR
	(*SelectorIR)(nil),  // 10: rule.SelectorIR
	(*ExclusionIR)(nil), // 11: rule.ExclusionIR
	(*TargetRefIR)(nil), // 12: rule.TargetRefIR
	(*RuleIR)(nil),      // 13: rule.RuleIR
	(*CheckIR)(nil),     // 14: rule.CheckIR
}
var file_rule_proto_depIdxs = []int32{
	9,  // 0: rule.SpecIR.adr:type_name -> rule.AdrIR
	10, // 1: rule.SpecIR.selectors:type_name -> rule.SelectorIR
	13, // 2: rule.SpecIR.rules:type_name -> rule.RuleIR
	0,  // 3: rule.SpecIR.mode:type_name -> rule.InvocationMode
	1,  // 4: rule.SelectorIR.kind:type_name -> rule.SelectorKind
	6,  // 5: rule.ExclusionIR.kind:type_name -> rule.ExcludeKind
	1,  // 6: rule.TargetRefIR.type:type_name -> rule.SelectorKind
	12, // 7: rule.TargetRefIR.scope:type_name -> rule.TargetRefIR
	2,  // 8: rule.RuleIR.kind:type_name -> rule.RuleKind
	12, // 9: rule.RuleIR.from:type_name -> rule.TargetRefIR
	12, // 10: rule.RuleIR.targets:type_name -> rule.TargetRefIR
	5,  // 11: rule.RuleIR.severity:type_name -> rule.Severity
	11, // 12: rule.RuleIR.excludes:type_name -> rule.ExclusionIR
	14, // 13: rule.RuleIR.checks:type_name -> rule.CheckIR
	3,  // 14: rule.RuleIR.visibility:type_name -> rule.Visibility
	4,  // 15: rule.RuleIR.type_constraint:type_name -> rule.TypeConstraint
	7,  // 16: rule.CheckIR.kind:type_name -> rule.CheckKind
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_rule_proto_init() }
func file_rule_proto_init() {
	if File_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rule_proto_rawDesc), len(file_rule_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rule_proto_goTypes,
		DependencyIndexes: file_rule_proto_depIdxs,
		EnumInfos:         file_rule_proto_enumTypes,
		MessageInfos:      file_rule_proto_msgTypes,
	}.Build()
	File_rule_proto = out.File
	file_rule_proto_goTypes = nil
	file_rule_proto_depIdxs = nil
}
